'use client'

import './globalStyle.scss'
import type { Metadata } from 'next'
import { NextUIProvider } from '@nextui-org/react'
import Layout from '@/view/layout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <Layout component={children} />
        </NextUIProvider>
      </body>
    </html>
  )
}
